changelog:
  categories:
    - title: '🔥 Breaking Changes'
      labels:
        - 'breaking'
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'hotfix'
        - 'bugfix'
        - 'bug'
    - title: '👋 Deprecated'
      labels:
        - 'deprecation'
    - title: '🔗 Dependency Updates'
      labels:
        - 'library-update'
        - 'dependencies'
    - title: '🛠  Internal Updates'
      labels:
        - 'update'
        - 'internal'
    - title: '📚 Docs'
      labels:
        - 'doc'
        - 'documentation'
