name: Scala CI
on:
  pull_request:
    branches: [ "master" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt

      - name: Check scalafmt
        run: sbt scalafmtCheckAll

      - name: Check build
        run: sbt clean compile test doc